### ISSUE TITLE
About the paper?

### ISSUE THREAD

**Issue by ge200012** [DrugD/RMCD#1]
May I ask where the link to this paper is? I cannot find the title of this paper.

**Comment by DrugD** [comment]
正在准备nips，过两天就有了，还在写



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/21/2024 22:42 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [DrugD/RMCD] About the paper? (Issue #1) |

May I ask where the link to this paper is? I cannot find the title of this paper.

**Comment by ge200012** [comment]
相信你一定可以的，please看一下邮箱

**Comment by DrugD** [comment]
那个邮箱我老师的，你是发给我老师了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月23日 23:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [DrugD/RMCD] About the paper? (Issue #1) |

相信你一定可以的，please看一下邮箱

**Comment by ge200012** [comment]
你的邮箱我应该也发了的

**Comment by ge200012** [comment]
**_k** 这个

**Comment by DrugD** [comment]
你有事吗，发邮箱 ***@***.***



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月24日 00:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [DrugD/RMCD] About the paper? (Issue #1) |

_k 这个

**Comment by ge200012** [comment]
就是想问一下这项工作有放在arxiv上吗

**Comment by DrugD** [comment]
已经上传了，过几天会发布



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月24日 12:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [DrugD/RMCD] About the paper? (Issue #1) |

就是想问一下这项工作有放在arxiv上吗
